import SidebarWrapper from "@/components/v4/sidebar-wrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout V4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarWrapper>{children}</SidebarWrapper>
      </body>
    </html>
  );
}
