import Sidebar from "@/components/v1/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout V1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-row gap-2 bg-dark-100">
          <div className="w-full bg-dark-100 h-dvh overflow-y-auto no-scrollbar py-2 pl-2">
            {children}
          </div>
          <Sidebar />
        </main>
      </body>
    </html>
  );
}
