import Navbar from "@/components/v2/navbar";
import Sidebar from "@/components/v2/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout V1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="main-wrapper">
          <Sidebar />
          <div className="w-full">
            <Navbar />
            <div className="main-content-with-navbar">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
