import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";
import styles from "@/styles/component/layout.module.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Dashboard Layout V6",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="overflow-hidden h-dvh">
          <Navbar />
          <main
            className={cn(
              "h-[calc(100vh-var(--h-navbar))]",
              styles.main_wrapper,
            )}
          >
            <Sidebar height="h-[calc(100vh-var(--h-navbar)]" />
            <main className={styles.main_content_with_navbar}>{children}</main>
            <Sidebar height="h-[calc(100vh-var(--h-navbar)]" />
          </main>
        </div>
      </body>
    </html>
  );
}
