import LayoutWrapper from "@/components/v6/layout-wrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout V6",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
