import Sidebar from "@/components/v3/sidebar";
import type { Metadata } from "next";
import styles from "@/styles/component/layout.module.css";

export const metadata: Metadata = {
  title: "Dashboard Layout V3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main_wrapper}>
          <Sidebar />
          <main className={`${styles.main_content} pr-2`}>{children}</main>
        </main>
      </body>
    </html>
  );
}
