import Sidebar from "@/components/v3/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout V5",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="main-wrapper">
          <Sidebar />
          <div className="main-content pr-2">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
