import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";
import styles from "@/styles/component/layout.module.css";

export const metadata: Metadata = {
  title: "Dashboard Layout V5",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main_wrapper}>
          <Sidebar />
          <main className={styles.main_content}>{children}</main>
          <Sidebar />
        </main>
      </body>
    </html>
  );
}
